const $ = (s) => document.querySelector(s);
const titleScreen = $('#titleScreen'), playScreen = $('#playScreen'), endingScreen = $('#endingScreen');
const storyText = $('#storyText'), choicesEl = $('#choices'), customForm = $('#customForm');
const AI_ENDPOINT = (window.HEARTBREAK_CONFIG?.apiEndpoint || '').replace(/\/$/, '');
const AI_TIMEOUT_MS = 20000;

const phases = [
  {date:'高二升高三暑假・七月下旬',time:'21:47',speaker:'手機螢幕',text:'暑期輔導講義攤在書桌上。手機亮起，班群裡有人問明天下午要不要去「暮光」打電動。\n\n杜承翰標記了喬子言。他只回：「都行啊，有人會玩就來。」',phone:'喬子言新增了一則限時動態。',opts:['在班群回覆：「我也可以去嗎？」','私訊林以晴，問明天有哪些人','只按住那則訊息，沒有送出任何字']},
  {date:'暑期輔導・第一週',time:'07:36',speaker:'早晨',text:'教室只開了一半的燈。喬子言趴在靠窗座位補眠，桌角擺著一罐沒開的咖啡。你的座位和他隔著兩排。',phone:'班群有人抱怨暑輔第一天就小考。',opts:['從他桌邊經過時輕敲桌面','把多買的咖啡放到他桌角','坐回自己的位置整理講義']},
  {date:'暑期輔導・第二週',time:'16:18',speaker:'放學後',text:'午後雷陣雨把走廊打成一片灰白。屋簷下擠滿沒帶傘的人。喬子言站在販賣機旁，低頭滑著手機。',phone:'氣象通知：大雨預計持續四十分鐘。',opts:['問他要不要一起等雨停','傳訊息問他有沒有帶傘','去合作社買東西，晚一點再走']},
  {date:'暑期輔導・最後一週',time:'12:22',speaker:'教室',text:'數學老師臨時宣布兩人一組訂正考卷。座位開始移動，椅腳摩擦地面。喬子言拿著卷子站起來，朝你這排看了一眼。',phone:'LINE 收到一則新訊息。',opts:['抬手問他要不要一組','先問旁邊的林以晴是否有組員','低頭整理自己的錯題']},
  {date:'高三上學期・開學日',time:'10:06',speaker:'新座位',text:'重新抽籤後，你的位置在喬子言斜後方。導師把升學行事曆貼上黑板，紅筆一路圈到明年五月。',phone:'喬子言在 Threads 寫：「最後一年。」',opts:['下課時問他暑假遊戲打到哪裡','借口確認課表，轉身和他說話','把新的行事曆抄進筆記本']},
  {date:'高三上學期・九月',time:'17:11',speaker:'體育館',text:'班際籃球練習剛結束。喬子言坐在看台最下排綁鞋帶，幾個人正在約晚餐。他抬頭問：「許漆漆，妳等一下有事嗎？」',phone:'林以晴傳來：「妳還在學校？」',opts:['回答：「沒有，怎麼了？」','問：「你們要去哪裡？」','說自己得先回家']},
  {date:'高三上學期・十月',time:'20:35',speaker:'晚自習',text:'停電只有幾秒。燈再亮時，全班響起一陣笑聲。你的橡皮擦滾到走道，停在喬子言鞋邊。',phone:'手機目前沒有新通知。',opts:['請他幫忙撿起來','自己走過去撿','暫時不用橡皮擦']},
  {date:'高三上學期・期中考後',time:'18:04',speaker:'公車站',text:'補習街的公車站擠滿學生。喬子言站在路線圖前，看見你時向旁邊挪了一步，空出遮雨棚內的位置。',phone:'公車預計 9 分鐘後抵達。',opts:['站到他旁邊，聊今天的考題','問他是不是也搭同一路車','在稍遠的位置等車']},
  {date:'高三上學期・校慶前',time:'15:40',speaker:'教室',text:'班上決定攤位要做懷舊遊戲屋。工作分配表從前排傳下來，喬子言的名字寫在器材組。你還沒有填。',phone:'班群正在統計校慶值班時段。',opts:['在器材組後面寫下名字','選擇比較需要人手的宣傳組','先詢問同學各組還缺多少人']},
  {date:'高三上學期・校慶',time:'19:26',speaker:'操場邊',text:'收攤後，彩色燈泡還掛在帳篷骨架上。喬子言把最後一箱道具放下，遞給你一瓶水：「今天謝啦，妳超可靠。」',phone:'Instagram 有人標註了班級合照。',opts:['接過水，問他要不要一起拍照','笑著回：「你現在才知道？」','說聲謝謝，去幫忙集合垃圾']},
  {date:'高三上學期・十一月',time:'23:08',speaker:'LINE',text:'你和喬子言因為校慶道具開始偶爾傳訊息。今晚他丟來一張遊戲戰績截圖，接著寫：「我隊友真的很扯。」',phone:'喬子言正在輸入訊息……',opts:['問他要不要下次一起排','回一張表示無言的貼圖','問他怎麼突然傳給你']},
  {date:'高三上學期・第二次段考',time:'16:52',speaker:'圖書館',text:'閱覽桌只剩你對面的位置。喬子言抱著參考書停下來，用氣音問：「這裡有人嗎？」',phone:'手機已切換為靜音。',opts:['搖頭，替他移開桌上的講義','小聲說：「你坐啊。」','指向另一邊剛空出的座位']},
  {date:'高三上學期・十二月',time:'17:34',speaker:'校門口',text:'風把制服外套吹得貼緊手臂。喬子言和一名你沒見過的短髮女生站在便利商店前。女生把一袋熱食遞給他，他接過時笑得很熟稔。',phone:'林以晴傳來一個問號。',opts:['照原路走過去，和他打招呼','轉進旁邊的文具店','傳訊息問林以晴看見了什麼']},
  {date:'高三上學期・聖誕節前',time:'13:05',speaker:'班級交換禮物',text:'抽籤紙在餅乾盒裡沙沙作響。你抽到喬子言的名字。規則是三百元以內，不能直接問本人想要什麼。',phone:'喬子言按讚了一則遊戲周邊貼文。',opts:['挑一個他提過的遊戲角色吊飾','買實用的暖暖包和零食組','請杜承翰幫忙打聽']},
  {date:'高三寒假・除夕前',time:'00:16',speaker:'深夜',text:'班群的聊天已經停了。喬子言半小時前傳來：「妳上次送的吊飾我掛書包了，謝啦。」螢幕上只有這一句。',phone:'訊息顯示已讀。',opts:['回：「你喜歡就好，新年快樂。」','問他怎麼還沒睡','只傳一張新年貼圖']},
  {date:'高三下學期・開學',time:'11:58',speaker:'走廊',text:'模擬考成績貼在辦公室外。喬子言站在人群後方，手裡捲著成績單。他看見你，問：「妳志願想填哪裡？」',phone:'升學網站提醒志願探索測驗。',opts:['說出最想去的學校，再問他的打算','半開玩笑說：「看你考去哪。」','回答還沒決定']},
  {date:'高三下學期・二月',time:'17:48',speaker:'自習教室',text:'大家走得差不多了。喬子言把筆蓋扣上，說他卡在英文作文，問你能不能幫忙看一下。窗外天色已經暗了。',phone:'末班公車還有 43 分鐘。',opts:['坐到他旁邊一起修改','請他把文章拍照傳給你','告訴他明天早自習再看']},
  {date:'高三下學期・三月',time:'14:20',speaker:'模擬考午後',text:'喬子言把一顆薄荷糖放到你桌上：「妳臉色很差，還好嗎？」教室裡有人趴著睡，有人在對答案。',phone:'健康中心目前開放。',opts:['說沒事，收下薄荷糖','坦白說昨晚幾乎沒睡','把糖推回去，叫他自己吃']},
  {date:'高三下學期・春雨',time:'18:12',speaker:'騎樓下',text:'你和喬子言又被同一場雨困住。這次他撐著一把深藍色的傘，往校門外走了兩步，回頭問：「妳去哪一站？」',phone:'雨勢預計持續一小時。',opts:['告訴他車站方向','說有人會來接','問他方不方便一起走']},
  {date:'高三下學期・四月',time:'21:03',speaker:'Threads',text:'喬子言發了一張舊遊戲主機的照片，文字只有：「突然找到以前的東西。」照片角落露出兩張拍立得，其中一張像是他和某個女生。',phone:'這則串文發布於 3 分鐘前。',opts:['按讚，不留言','留言問那是什麼遊戲','私訊問照片裡的人是誰']},
  {date:'高三下學期・考前倒數',time:'19:44',speaker:'教室',text:'倒數牌剩下三十七天。喬子言把寫滿算式的便條紙揉成一團，投進垃圾桶，沒有投進。',phone:'杜承翰在班群約考完去唱歌。',opts:['撿起紙團丟進垃圾桶','問他是不是壓力很大','把自己的巧克力放到他桌上']},
  {date:'高三下學期・五月',time:'06:56',speaker:'清晨',text:'你比平常早到。喬子言已經坐在教室後門旁，戴著耳機背單字。日光從窗簾縫裡切過他的課本。',phone:'今日第一節為國文複習考。',opts:['坐到附近一起念書','傳訊息問他在聽什麼','不打擾他，回自己的座位']},
  {date:'大考結束',time:'17:23',speaker:'校門外',text:'最後一科結束，人群像水一樣湧出校門。喬子言被杜承翰勾著肩，遠遠朝你喊：「許漆漆，晚上唱歌要來喔！」',phone:'班群投票：今晚 19:00 聚餐唱歌。',opts:['大聲回他：「好！」','走近確認地點和時間','傳訊息說晚一點再決定']},
  {date:'畢業前・班級旅行',time:'22:14',speaker:'民宿露台',text:'其他人在客廳玩桌遊。喬子言靠著欄杆喝汽水，旁邊空著一張塑膠椅。遠處海面看不見，只聽得到浪。',phone:'Instagram 收到 4 則標註通知。',opts:['走過去坐在空椅上','從門邊問他要不要玩桌遊','留在客廳和大家合照']},
  {date:'畢業前・五月底',time:'15:17',speaker:'空教室',text:'喬子言來拿忘記的外套。教室只剩你們兩個。他套上外套，拉鍊拉到一半，忽然說：「時間過好快喔。」',phone:'畢業典禮倒數 9 天。',opts:['說：「我有點不想畢業。」','問他大學還會不會聯絡','笑著說總算可以離開學校']},
  {date:'畢業前・六月',time:'20:51',speaker:'LINE',text:'喬子言傳來一張錄取畫面的截圖。他要去北部，而你填的第一志願留在南部。過了兩分鐘，他又傳：「妳的呢？」',phone:'喬子言的訊息尚未讀取。',opts:['傳自己的錄取結果並恭喜他','回：「以後很難見面了耶。」','先不回，關掉螢幕']},
  {date:'畢業典禮前三天',time:'16:33',speaker:'樓梯間',text:'畢業紀念冊在班上傳了一整天。喬子言把你的那本遞回來：「我寫好了，不准現在看。」封底夾著一張拍立得，是校慶那天的班級合照。',phone:'相簿新增一張照片。',opts:['問他為什麼不能現在看','請他也把紀念冊交給你寫','答應他回家再看']},
  {date:'畢業典禮前夕',time:'23:41',speaker:'房間',text:'紀念冊翻到喬子言那頁。他寫了很長一段：謝謝你的筆記、校慶、模擬考前的糖，還有那些放學後的訊息。最後一行是：「妳是我高中最重要的朋友之一。」',phone:'喬子言目前在線上。',opts:['傳訊息問他明天能不能單獨聊聊','把那一頁拍下來，沒有聯絡他','先寫下明天想說的話']},
  {date:'畢業典禮・散場後',time:'16:08',speaker:'舊教學樓',text:'禮堂的人聲逐漸遠了。喬子言抱著畢業花束站在窗邊，領口被六月的風掀起一角。他看見你，停下原本要離開的腳步。\n\n「妳找我？」',phone:'手機已切換為靜音。',opts:['說：「我有一件事想親口告訴你。」','把準備好的信交給他','問他能不能陪你走到校門口']}
];

const state = {round:0, friendship:0, memories:[], custom:[], sound:true, reason:['白月光','純粹無感','心在遠方'][Math.floor(Math.random()*3)]};
const impacts = [[6,4,1],[4,6,1],[5,3,1]];
function save(){localStorage.setItem('heartbreak-save',JSON.stringify(state));}
function load(){const s=localStorage.getItem('heartbreak-save');if(s) Object.assign(state,JSON.parse(s));}
function typeText(text){storyText.innerHTML='';let i=0;const cursor=document.createElement('span');cursor.className='cursor';const tick=()=>{storyText.textContent=text.slice(0,i++);storyText.append(cursor);if(i<=text.length)setTimeout(tick,Math.max(8,24-text.length/20));else cursor.remove();};tick();}
function render(){if(state.round>=29){renderFinalRound();return}const e=phases[state.round];$('#chapterLabel').textContent=`CHAPTER ${String(state.round+1).padStart(2,'0')}`;$('#dateLabel').textContent=e.date;$('#timeLabel').textContent=e.time;$('#speaker').textContent=e.speaker;$('#progressBar').style.width=`${(state.round+1)/30*100}%`;typeText(e.text);renderChoices(e);setAIStatus(AI_ENDPOINT?'online':'offline');$('#phoneDot').classList.remove('hidden');choicesEl.classList.remove('hidden');customForm.classList.add('hidden');$('#continueArea').classList.add('hidden');$('#nextBtn').classList.remove('hidden');save();}
function renderChoices(e){choicesEl.innerHTML='';[...e.opts,'自由輸入想說的話或採取的行動'].forEach((t,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${'ABCD'[i]}</b><span>${t}</span>`;b.onclick=()=>i===3?openCustom():choose(i,t);choicesEl.append(b);});}
function openCustom(){choicesEl.classList.add('hidden');customForm.classList.remove('hidden');$('#customInput').focus();}
async function choose(i,text,isCustom=false){const e=phases[state.round];const add=isCustom?customImpact(text):(impacts[state.round%impacts.length][i]||2);state.friendship=Math.min(100,state.friendship+add);if(add>=5)state.memories.push(e.date);if(isCustom)state.custom.push(text);choicesEl.classList.add('hidden');customForm.classList.add('hidden');$('#continueArea').classList.remove('hidden');$('#nextBtn').classList.add('hidden');$('#consequence').innerHTML='<span class="ai-wait">正在等待故事回應</span>';setAIStatus(AI_ENDPOINT?'thinking':'offline');let r;try{r=AI_ENDPOINT?await requestAIReply(text,isCustom,e):offlineResponse(i,text,isCustom,e);setAIStatus(AI_ENDPOINT?'online':'offline');}catch(error){console.warn('AI reply unavailable:',error.message);r=offlineResponse(i,text,isCustom,e);setAIStatus('error');r+='\n\n（目前使用離線劇情；稍後可再嘗試 AI 回應。）';}if((state.round+1)%4===0)r+='\n\n離開前，他叫住你，把剛才沒說完的事補完。你們在走廊多站了一會兒。';$('#consequence').textContent=r;$('#nextBtn').classList.remove('hidden');save();tone(520,.06);}
function offlineResponse(i,text,isCustom,e){const responses=[`你照自己選的方式做了。喬子言先是愣了一下，隨後自然地接住話題。周圍的聲音很快又流動起來，像這只是一段普通的日常。`,`喬子言看了你一眼，回了一句簡短的話。那句話不冷淡，也沒有比表面更多的意思。`,`事情沒有停留太久。幾分鐘後，話題被別人接走，眼前的場景也往下一件事推進。`];return isCustom?customResponse(text,e):responses[i%3];}
function setAIStatus(mode){const el=$('#aiStatus');if(!el)return;el.className='ai-status'+(mode==='offline'?'':` ${mode}`);el.querySelector('span').textContent={online:'AI 劇情',thinking:'AI 思考中',error:'離線備援',offline:'離線劇情'}[mode]||'離線劇情';}
async function requestAIReply(action,isCustom,scene){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),AI_TIMEOUT_MS);try{const response=await fetch(`${AI_ENDPOINT}/reply`,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({round:state.round+1,totalRounds:30,player:{name:'許漆漆',gender:'女',stage:'高中'},character:{name:'喬子言',gender:'男',traits:'直男、愛打遊戲、看似宅但其實是現充、成績不錯'},scene:{date:scene.date,time:scene.time,speaker:scene.speaker,text:scene.text},action:String(action).slice(0,120),isCustom,friendship:state.friendship,hiddenReason:state.reason,memories:state.memories.slice(-6),recentCustomActions:state.custom.slice(-4)}),});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`AI service ${response.status}`);if(typeof data.reply!=='string'||data.reply.trim().length<8)throw new Error('Invalid AI reply');return data.reply.trim();}finally{clearTimeout(timer);}}
function customImpact(t){return /幫|陪|問|一起|分享|傳|笑|謝/.test(t)?5:/告白|喜歡你|交往|親|抱/.test(t)?2:3;}
function customResponse(t,e){if(/告白|喜歡你|交往/.test(t)&&state.round<29)return `你把「${t}」說出口。喬子言的神情停了一瞬，目光移向旁邊。\n\n「妳今天怎麼怪怪的？」他笑了一下，語氣刻意放輕。遠處有人喊他的名字，他順勢回過頭。`;if(/親|抱|牽/.test(t))return `你試著做出那個動作。喬子言下意識往旁邊讓了半步，接著像要化解尷尬似地問起另一件事。距離重新回到平常的位置。`;return `你選擇：「${t}」\n\n喬子言依照眼前發生的事回應了你。對話持續了一陣，直到${e.date.includes('晚')?'手機螢幕暗下來':'周圍有人走近'}，這段短暫的交集才告一段落。`;}
function next(){if(state.round>=29){showEnding();return}state.round++;const card=$('.dialogue-card');card.classList.add('fade-scene');setTimeout(()=>{card.classList.remove('fade-scene');render();},420);}
function renderFinalRound(){const e=phases[29];$('#chapterLabel').textContent='CHAPTER 30';$('#dateLabel').textContent=e.date;$('#timeLabel').textContent=e.time;$('#speaker').textContent=e.speaker;$('#progressBar').style.width='100%';typeText(e.text);renderChoices(e);choicesEl.querySelectorAll('.choice').forEach((b,i)=>b.onclick=()=>i===3?openCustom():finalChoice(i,e.opts[i]));$('#continueArea').classList.add('hidden');save();}
function finalChoice(i,t){choicesEl.classList.add('hidden');customForm.classList.add('hidden');state.custom.push(t);$('#consequence').textContent=confessionResult();$('#continueArea').classList.remove('hidden');$('#nextBtn').textContent='看完這個夏天 →';$('#nextBtn').onclick=showEnding;save();}
function confessionResult(){if(state.friendship>=85)return '你終於把藏了很久的話說完。\n\n喬子言一直沒有打斷。風把花束的包裝紙吹得窸窣作響。過了很久，他低聲說：「漆漆，對不起。妳真的、真的對我很重要……可是我沒辦法用妳希望的方式喜歡妳。」\n\n他沒有逃走，也沒有敷衍。正因為每個字都很溫柔，才沒有任何可以誤解的餘地。';if(state.friendship>=45)return '你把話說完後，喬子言握緊了花束。\n\n「我很喜歡跟妳聊天，也一直把妳當很好的朋友。」他停了一下，「但如果是交往，我真的沒有那種感覺。對不起。」\n\n禮堂外傳來拍照的倒數聲，三、二、一，接著是一大片歡呼。';return '你說完後，喬子言沉默了幾秒。\n\n「對不起，我不知道妳是這樣想的。」他把聲音放得很輕，「我一直只把妳當同學。我不想騙妳說以後可能會有機會。」\n\n他把拒絕說得清楚。窗外的畢業氣球正一顆一顆升高。';}
function showEnding(){playScreen.classList.add('hidden');endingScreen.classList.remove('hidden');let title='六月沒有回信';if(state.friendship>=85)title='最重要的朋友之一';else if(state.memories.length>=4)title='那些差一點的時刻';$('#endingTitle').textContent=title;$('#endingText').textContent=`後來，你們仍在社群軟體上留著彼此。大學開學後，訊息從每天變成每週，再變成節日時的一句問候。\n\n有一年，喬子言在你生日那天傳來：「生日快樂，好久不見。」你看著那四個字，沒有再從裡面尋找別的意思。\n\n那不是一段失敗的戀愛。因為它從來沒有開始。可是那個夏天確實存在過——和所有沒有被選中的心意一樣，安靜、完整，而且無法退回。`;localStorage.removeItem('heartbreak-save');}

function phoneHome(){const e=phases[Math.min(state.round,29)];$('#phoneContent').innerHTML=`<div class="phone-head">手機主頁</div><div class="phone-home"><div class="app-grid"><button class="app" data-app="line"><span class="app-icon line-icon">L</span>LINE</button><button class="app" data-app="threads"><span class="app-icon threads-icon">＠</span>Threads</button><button class="app" data-app="ig"><span class="app-icon ig-icon">◎</span>Instagram</button></div><div class="notification"><strong>最新通知</strong>${e.phone}<br><small>點選應用程式查看</small></div><div class="notification"><strong>遊戲提示</strong>可不限次數查看手機；關閉後才會回到當前選擇。</div></div>`;document.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>phoneApp(b.dataset.app));}
function phoneApp(app){const n=state.round;let name=app==='line'?'LINE':app==='threads'?'Threads':'Instagram';let body=app==='line'?`<div class="chat-item"><strong>喬子言</strong>${n>9?'剛剛那個真的超好笑':'尚無私人訊息'}<br><small>${n>9?'已讀':'—'}</small></div><div class="chat-item"><strong>林以晴</strong>妳明天會去嗎？<br><small>未讀</small></div><div class="chat-item"><strong>高二仁班暑期生存群</strong>杜承翰：有人會玩就來<br><small>13 則未讀訊息</small></div>`:app==='threads'?`<div class="post"><strong>@ziyan_q</strong><br>${n>18?'突然找到以前的東西。':'暑輔第一天就要小考是認真的嗎'}<br><small>♡ ${12+n}　回覆 ${n%4}</small></div><div class="post"><strong>@chenghan_d</strong><br>缺一個，來會玩的。<br><small>♡ 8</small></div>`:`<div class="post"><strong>ziyan_q 的限時動態</strong><br>${n>22?'「結束了。」——校門口的天空':'遊戲勝利畫面，角落拍到半杯冰紅茶。'}<br><small>${n%3===0?'你尚未查看':'已查看'}</small></div><div class="post"><strong>通知</strong><br>${n>8?'你被標註在班級合照中。':'林以晴按讚了你的限時動態。'}</div>`;$('#phoneContent').innerHTML=`<button class="app-back">‹ 手機主頁</button><div class="phone-head">${name}</div><div class="phone-home">${body}</div>`;$('.app-back').onclick=phoneHome;}
function openPhone(){phoneHome();$('#phoneTime').textContent=phases[Math.min(state.round,29)].time;$('#phoneModal').classList.remove('hidden');$('#phoneDot').classList.add('hidden');tone(680,.04);}
function resetGame(){localStorage.removeItem('heartbreak-save');Object.assign(state,{round:0,friendship:0,memories:[],custom:[],reason:['白月光','純粹無感','心在遠方'][Math.floor(Math.random()*3)]});endingScreen.classList.add('hidden');titleScreen.classList.remove('hidden');playScreen.classList.add('hidden');$('#confirmModal').classList.add('hidden');$('#nextBtn').textContent='繼續 →';$('#nextBtn').onclick=next;}
let audioCtx;function tone(freq,dur){if(!state.sound)return;audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.025,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}
function start(resume=false){if(resume)load();else localStorage.removeItem('heartbreak-save');titleScreen.classList.add('hidden');endingScreen.classList.add('hidden');playScreen.classList.remove('hidden');render();}

for(let i=0;i<22;i++){const d=document.createElement('i');d.style.left=Math.random()*100+'%';d.style.top=(45+Math.random()*55)+'%';d.style.animationDelay=Math.random()*9+'s';d.style.animationDuration=(7+Math.random()*7)+'s';$('#dust').append(d)}
$('#startBtn').onclick=()=>start(false);if(localStorage.getItem('heartbreak-save'))$('#continueBtn').classList.remove('hidden');$('#continueBtn').onclick=()=>start(true);$('#nextBtn').onclick=next;$('#phoneBtn').onclick=openPhone;$('#closePhone').onclick=()=>$('#phoneModal').classList.add('hidden');$('#phoneModal').onclick=e=>{if(e.target===$('#phoneModal'))$('#phoneModal').classList.add('hidden')};$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').classList.toggle('sound-off',!state.sound);save();tone(600,.05)};$('#resetBtn').onclick=()=>$('#confirmModal').classList.remove('hidden');$('#cancelReset').onclick=()=>$('#confirmModal').classList.add('hidden');$('#confirmReset').onclick=resetGame;$('#endingRestart').onclick=resetGame;$('#cancelCustom').onclick=()=>{customForm.classList.add('hidden');choicesEl.classList.remove('hidden')};customForm.onsubmit=e=>{e.preventDefault();const t=$('#customInput').value.trim();if(!t){customForm.classList.add('shake');setTimeout(()=>customForm.classList.remove('shake'),400);return}$('#customInput').value='';if(state.round===29){state.friendship=Math.min(100,state.friendship+customImpact(t));state.custom.push(t);finalChoice(3,t)}else choose(3,t,true)};
